# High-performance static+search server. No nginx, no JS: pages are
# pre-generated by the crawler, /search is rendered server-side from
# data/shards.json kept in memory with mtime-based hot reload.

require "http/server"
require "./models"
require "./categories"
require "./render"
require "./search"

module Catalog
  class App
    include HTTP::Handler
    @mtime : Time? = nil
    @site : SiteData

    def initialize(@data_path : String, @public_dir : String)
      @mutex = Mutex.new
      @site = SiteData.load(@data_path)
      @mtime = file_mtime
      STDERR.puts "loaded #{@site.shards.size} shards from #{@data_path}"

      spawn reload_watcher
    end

    def call(context : HTTP::Server::Context)
      path = context.request.path

      if path == "/search"
        return search(context)
      elsif path == "/new"
        return newly(context)
      elsif path == "/activity"
        return activity(context)
      elsif path.starts_with?("/category/") && !path.ends_with?(".html")
        return category(context)
      end

      # Clean URLs: rewrite to the pre-generated index.html of the section.
      if path == "/"
        context.request.path = "/index.html"
      elsif path == "/categories"
        context.request.path = "/categories/index.html"
      elsif path.starts_with?("/shards/") && !path.ends_with?(".html")
        context.request.path = path + ".html"
      end

      call_next(context)
    end

    private def search(context : HTTP::Server::Context)
      params = HTTP::Params.parse(context.request.query || "")
      q = params["q"]?.to_s
      sort = params["sort"]?
      filter5 = params["filter"]? == "5y"

      site = current_site
      base = Listing.filtered(site.shards, filter5)

      if q.strip.empty?
        # Empty query: fall back to the most starred shards instead of a dead end.
        results = Listing.sorted(base, sort || "stars").first(30)
      else
        results = ShardSearch.new(base).query(q)
        results = Listing.sorted(results, sort)
      end

      html = Render.search(q, results, base.size, sort, filter5)
      context.response.content_type = "text/html; charset=utf-8"
      context.response.headers["Cache-Control"] = "public, max-age=60"
      context.response.print html
    end

    private def newly(context : HTTP::Server::Context)
      params = HTTP::Params.parse(context.request.query || "")
      site = current_site

      if month = params["month"]?
        return call_next(context) unless month =~ /^\d{4}-\d{2}$/
        y = month[0, 4].to_i
        m = month[5, 2].to_i
        shards = site.shards
          .select { |s| s.created_time.year == y && s.created_time.month == m }
          .sort_by { |s| -s.created_time.to_unix }
        html = Render.new_shards("month", month, shards, site.shards.size)
        context.response.content_type = "text/html; charset=utf-8"
        context.response.headers["Cache-Control"] = "public, max-age=300"
        context.response.print html
        return
      end

      period = params["period"]? || "week"
      days = Render::NEW_PERIODS[period]?
      return call_next(context) unless days # unknown period -> 404

      cutoff = Time.utc - Time::Span.new(days: days)
      shards = site.shards
        .select { |s| s.created_time > cutoff }
        .sort_by { |s| -s.created_time.to_unix }

      html = Render.new_shards(period, nil, shards, site.shards.size)
      context.response.content_type = "text/html; charset=utf-8"
      context.response.headers["Cache-Control"] = "public, max-age=300"
      context.response.print html
    end

    private def activity(context : HTTP::Server::Context)
      site = current_site
      html = Render.activity(site)
      context.response.content_type = "text/html; charset=utf-8"
      context.response.headers["Cache-Control"] = "public, max-age=300"
      context.response.print html
    end

    private def category(context : HTTP::Server::Context)
      slug = context.request.path.split("/")[2]?.to_s.chomp("/")
      params = HTTP::Params.parse(context.request.query || "")
      sort = params["sort"]?
      filter5 = params["filter"]? == "5y"

      site = current_site
      shards = site.shards.select(&.category.==(slug))

      if shards.empty? && !CATEGORY_TITLES[slug]?
        call_next(context) # unknown category -> 404
        return
      end

      shards = Listing.sorted(Listing.filtered(shards, filter5), sort || "stars")
      html = Render.category(slug, shards, sort, filter5)
      context.response.content_type = "text/html; charset=utf-8"
      context.response.headers["Cache-Control"] = "public, max-age=300"
      context.response.print html
    end

    def current_site : SiteData
      @mutex.synchronize { @site }
    end

    private def file_mtime : Time?
      File.info?(@data_path).try &.modification_time
    end

    private def reload_watcher
      loop do
        sleep 30.seconds
        m = file_mtime
        next unless m && m != @mtime
        @mutex.synchronize do
          begin
            @site = SiteData.from_json(File.read(@data_path))
            @mtime = m
            STDERR.puts "reloaded #{@site.shards.size} shards"
          rescue ex
            STDERR.puts "reload failed: #{ex.message}"
          end
        end
      end
    end
  end

  class CacheHeaders
    include HTTP::Handler

    def call(context : HTTP::Server::Context)
      call_next(context)
      return unless cacheable = context.request.path.starts_with?("/assets/")
      if context.response.status.ok?
        context.response.headers["Cache-Control"] = "public, max-age=86400"
      end
    end
  end
end

public_dir = ENV.fetch("PUBLIC_DIR", "public")
data_path = ENV.fetch("DATA_FILE", "data/shards.json")
port = ENV.fetch("PORT", "8080").to_i

app = Catalog::App.new(data_path, public_dir)
static = HTTP::StaticFileHandler.new(public_dir, fallthrough: true, directory_listing: false)

server = HTTP::Server.new([
  HTTP::LogHandler.new,
  HTTP::CompressHandler.new,
  HTTP::ErrorHandler.new,
  Catalog::CacheHeaders.new,
  app,
  static,
] of HTTP::Handler) do |context|
  context.response.status = :not_found
  context.response.content_type = "text/html; charset=utf-8"
  context.response.print Render.error(404, "This page does not exist.")
end

address = server.bind_tcp("0.0.0.0", port)
STDERR.puts "listening on http://#{address}"
server.listen
