# High-performance static+search server. No nginx, no JS: pages are
# pre-generated by the crawler, /search is rendered server-side from
# data/shards.json kept in memory with mtime-based hot reload.

require "http/server"
require "./models"
require "./categories"
require "./render"
require "./search"

module Catalog
  class App
    include HTTP::Handler
    @mtime : Time? = nil
    @site : SiteData

    def initialize(@data_path : String, @public_dir : String)
      @mutex = Mutex.new
      @site = SiteData.load(@data_path)
      @mtime = file_mtime
      STDERR.puts "loaded #{@site.shards.size} shards from #{@data_path}"

      spawn reload_watcher
    end

    def call(context : HTTP::Server::Context)
      path = context.request.path

      if path == "/search"
        return search(context)
      end

      # Clean URLs: rewrite to the pre-generated index.html of the section.
      if path == "/"
        context.request.path = "/index.html"
      elsif path == "/categories" || (path.starts_with?("/category/") && !path.ends_with?(".html"))
        context.request.path = path.chomp("/") + "/index.html"
      elsif path.starts_with?("/shards/") && !path.ends_with?(".html")
        context.request.path = path + ".html"
      end

      call_next(context)
    end

    private def search(context : HTTP::Server::Context)
      q = HTTP::Params.parse(context.request.query || "")["q"]?.to_s
      site = current_site
      results = ShardSearch.new(site.shards).query(q)
      html = Render.search(q, results, site.shards.size)
      context.response.content_type = "text/html; charset=utf-8"
      context.response.headers["Cache-Control"] = "public, max-age=60"
      context.response.print html
    end

    def current_site : SiteData
      @mutex.synchronize { @site }
    end

    private def file_mtime : Time?
      File.info?(@data_path).try &.modification_time
    end

    private def reload_watcher
      loop do
        sleep 30.seconds
        m = file_mtime
        next unless m && m != @mtime
        @mutex.synchronize do
          begin
            @site = SiteData.from_json(File.read(@data_path))
            @mtime = m
            STDERR.puts "reloaded #{@site.shards.size} shards"
          rescue ex
            STDERR.puts "reload failed: #{ex.message}"
          end
        end
      end
    end
  end

  class CacheHeaders
    include HTTP::Handler

    def call(context : HTTP::Server::Context)
      call_next(context)
      return unless cacheable = context.request.path.starts_with?("/assets/")
      if context.response.status.ok?
        context.response.headers["Cache-Control"] = "public, max-age=86400"
      end
    end
  end
end

public_dir = ENV.fetch("PUBLIC_DIR", "public")
data_path = ENV.fetch("DATA_FILE", "data/shards.json")
port = ENV.fetch("PORT", "8080").to_i

app = Catalog::App.new(data_path, public_dir)
static = HTTP::StaticFileHandler.new(public_dir, fallthrough: true, directory_listing: false)

server = HTTP::Server.new([
  HTTP::LogHandler.new,
  HTTP::CompressHandler.new,
  HTTP::ErrorHandler.new,
  Catalog::CacheHeaders.new,
  app,
  static,
] of HTTP::Handler) do |context|
  context.response.status = :not_found
  context.response.content_type = "text/html; charset=utf-8"
  context.response.print Render.error(404, "This page does not exist.")
end

address = server.bind_tcp("0.0.0.0", port)
STDERR.puts "listening on http://#{address}"
server.listen
